### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by Nolram12345** [W298/SurfelGI#22]
Hi! I wanted to check this implementation of Surfel GI out myself, but I couldn't quite figure out how to build the custom render passes against Falcor. Are there any instructions for this?

**Comment by W298** [comment]
This repository is currently still in development, so I don't recommend building and testing it right now (because there's code that is hard-coded and scene-specific), but I'll explain you through it briefly.

1. Put `SurfelGI/RenderPasses` into `SurfelGI/Falcor/Source/RenderPasses`
2. Edit `Falcor/Source/RenderPasses/CMakeLists.txt`
`add_subdirectory(Surfel)`
3. Follow Falcor's build instrcution (Build Mogwai).
4. Run Mogwai and use below script.
```
from pathlib import WindowsPath, PosixPath
from falcor import *

def render_graph_DefaultRenderGraph():
    g = RenderGraph('DefaultRenderGraph')
    g.create_pass('SurfelGI', 'SurfelGI', {})
    g.create_pass('SurfelGBuffer', 'SurfelGBuffer', {})
    g.create_pass('SurfelDirectLightingPass', 'SurfelDirectLightingPass', {})
    g.add_edge('SurfelGBuffer.packedHitInfo', 'SurfelGI.packedHitInfo')
    g.add_edge('SurfelGBuffer.packedHitInfo', 'SurfelDirectLightingPass.packedHitInfo')
    g.add_edge('SurfelGI.output', 'SurfelDirectLightingPass.indirectLighting')
    g.mark_output('SurfelDirectLightingPass.output')
    return g

DefaultRenderGraph = render_graph_DefaultRenderGraph()
try: m.addGraph(DefaultRenderGraph)
except NameError: None
```
5. Load scene.

Since the cell (used for searching surfels) sizes are hard-coded, you'll probably need to resize the scene down. I'll fix that later.

**Comment by Nolram12345** [comment]
Thanks! I'll be patient for now then and revisit this project once it's perhaps a little further along.
