### ISSUE TITLE
This case is used inside mogwai, it only works for Arcade, for other scenes it's black, is this a python script problem?

### ISSUE THREAD

**Issue by LiZhien712** [W298/SurfelGI#29]

**Comment by W298** [comment]
Sorry for the late comments.

Because that version (also current version) does not support global illumination for specular materials, it might appear black if direct illumination is not applied to that pixel.

Currently, I pushed the commit f2e968d, 2c5c7c2 that automatically modifies the properties of the specular material when the scene is loaded.
(I will use this method until support global illumination for the specular material.)

Also, I uploaded [pipeline script](https://github.com/W298/SurfelGI/blob/main/scripts/BasicSurfelGI.py). Try this.
